name: Publish RATLS Core Crate

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (skip cargo publish)'
        type: boolean
        default: true

env:
  CRATE_BASE_DIR: ${{ github.workspace }}/core

jobs:
  package:
    runs-on: ubuntu-latest
    outputs:
      hash: ${{ steps.hash.outputs.hash }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: 'false'
      - name: Prepare package
        run: |
          cd ${{ env.CRATE_BASE_DIR }}
          cargo package
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ratls-core-crate
          path: target/package/*.crate
      - name: generate hash
        id: hash
        run: cd target/package && echo "hash=$(sha256sum ./*.crate | base64 -w0)" >> "${GITHUB_OUTPUT}"

  provenance:
    if: ${{ !inputs.dry_run  }}
    needs: [package]
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0
    permissions:
      # Needed to detect the GitHub Actions environment
      actions: read
      # Needed to create the provenance via GitHub OIDC
      id-token: write
      # Needed to upload assets/artifacts
      contents: write
    with:
      # SHA-256 hashes of the Crate package.
      base64-subjects: ${{ needs.package.outputs.hash }}

  publish:
    runs-on: ubuntu-latest
    needs: [package]
    permissions:
      # Needed to create the draft release
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: 'true'

      - name: Publish crate.io package
        env:
          CRATES_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          DRY_RUN: ${{ inputs.dry_run && '--dry-run' || '' }}
        run: |
          cd ${{ env.CRATE_BASE_DIR }}
          # DRY_RUN expansion cannot be double quoted when variable contains empty string otherwise cargo publish 
          # would fail. This is safe since DRY_RUN is handled in the env section above.
          # shellcheck disable=SC2086
          cargo publish --token "${CRATES_TOKEN}" ${DRY_RUN}

      - name: Create draft release
        run: |
          VERSION=$(grep '^version = ' core/Cargo.toml | cut -d '"' -f2)
          export VERSION
          TAG="ratls-core-v${VERSION}"
          export TAG
          echo "version: ${VERSION}"
          echo "tag: ${TAG}"

          git tag "$TAG"
          git push origin "${TAG}"

          gh release create --draft --repo ${{ github.repository }} \
          --verify-tag "${TAG}" \
          --title "${TAG}" \
          target/package/*.crate
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Generate hash
        id: published_hash
        run: cd target/package && echo "pub_hash=$(sha256sum ./*.crate | base64 -w0)" >> "${GITHUB_OUTPUT}"

      - name: Compare hashes
        if: ${{ needs.package.outputs.hash != steps.published_hash.outputs.pub_hash }}
        run: |
          echo "ERROR: Published crate hash does not match the packaged crate hash!"
          exit 1
